# Generated by Django 5.2 on 2025-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="filetitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="sheet_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="worksheet_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
