# Generated by Django 5.2 on 2025-05-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionapi", "0002_customer_filetitle_customer_sheet_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dire", models.TextField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dires",
                        to="actionapi.action",
                    ),
                ),
            ],
        ),
    ]
