# Generated by Django 5.2 on 2025-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionapi", "0003_dire"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="dire_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Dire",
        ),
    ]
