# Generated by Django 5.2 on 2025-05-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionapi", "0004_action_dire_text_delete_dire"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="note1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="note2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="note3",
            field=models.TextField(blank=True, null=True),
        ),
    ]
